### ISSUE TITLE
Incorrect PSR namespace?

### ISSUE THREAD

**Issue by JoyceBabu** [wppunk/WPPlugin#5]
Autoload section of `composer.json` has the following entry

```
"PluginName\\Dependencies\\": "dependencies/psr/"
```

But isn't PSR dependencies loaded from `PluginName\Vendor`? I couldn't find any instances where `PluginName\Dependencies` is defined.

**Comment by wppunk** [comment]
@JoyceBabu Try to run the `composer scoper` command.

**Comment by JoyceBabu** [comment]
> @JoyceBabu Try to run the `composer scoper` command.

`composer scoper` creates the namespaced vendor classes including `PSR\*` to `dependencies\vendor\vendor\psr`.
The new namespace was `PluginName\Vendor\Psr`, and not `PluginName\Dependencies`.

**Comment by wppunk** [comment]
Oh, okay. This is just garbage. I'll remove it in the next release.
